    
---
- name: Create Tomcat user
  hosts: security_host
  gather_facts: false
  remote_user: root
  become: yes
    tasks:
    #- include_vars: var.yml       
    - name: Create a Tomcat User
      user:
          name: "Semaphore"
           
    - name: Create a Tomcat Group
      group:
        name: "Semaphore"
     
    - name: Create a Tomcat Directory
      file:
        path: /home/"Semaphore"
        owner: "Semaphore"
        group: "Semaphore"
        mode: 0755
        recurse: yes
        
    
